Backend rich lo l api
PoroRift/pororift-backend pull request #10
Opened 2018-08-30 03:53 UTC by RichCherng

Just barebone logic, need clean up

2018-08-30 03:55 UTC, cheriejw commented on src/LoLAPI/api.js
> +let key = fs.readFileSync('./api_key');
create a config file to import the key directly rather than using fs

2018-08-30 03:56 UTC, RichCherng commented on src/LoLAPI/api.js
> +let key = fs.readFileSync('./api_key');
yea, it's there for now. Need to create config file

2018-08-30 03:57 UTC, cheriejw commented on src/LoLAPI/api.js
> +let url_getStat = "https://na1.api.riotgames.com/lol/summoner/v3/summoners/by-name/"; // This need to be move out ot config file
Can use the URL_GETSTAT naming convention for constant values.

2018-08-30 03:58 UTC, cheriejw commented on src/LoLAPI/api.js
> +console.log(key.toString());
clean up

2018-08-30 03:59 UTC, cheriejw commented on src/LoLAPI/api.js
> +export var calcCircumference = (radius) => {
clean up

2018-08-30 04:00 UTC, cheriejw commented on src/LoLAPI/api.js
> +			console.log(" error request ", err);
change to '

2018-08-30 04:08 UTC, cheriejw requested changes

2018-08-30 04:08 UTC, cheriejw commented on src/LoLAPI/api.js
> +export let getSummonerStat = async (_summonerName) => {
Use 2 spaces as specified in design docs instead of tabs.

2018-08-30 04:08 UTC, cheriejw commented on src/index.js
> +import {getSummoner} from './LoLAPI/summoner.js'
`import { getSummoner } from './dshfkasdjhf.js'`;

2018-08-30 04:08 UTC, cheriejw commented on src/index.js
> +})
;

2018-08-30 04:35 UTC, RichCherng commented
Review POR FAAAAAVORRRR

2018-08-30 04:36 UTC, RichCherng commented
BUT DON'T MERGE

2018-08-30 09:35 UTC, cheriejw requested changes
for .babelrc please use newline after the curly brackets and indent with 2 spaces the "presets": ["env"] like you did in the front-end babelrc file.

You don't have to, but would be nice to add comment in .gitignore about what api_key is.

Again, since you are only using fs for reading you might as well import the actual key itself.

Why do you need circumference calculation?

Rename your branch

again, if you are using ES6 destructure please put spaces between the variables and curly braces.

you still have single quotes here. => summoner.js page

sometimes in the then you do `( (s)` and sometimes you do `((s)` ; pick one.

make sure to convert all tabs to 2 spaces. 

place ; at the end of each statement. youre missing it in `app.get("/champs...`

2018-08-30 09:36 UTC, cheriejw commented on src/LoLAPI/api.js
> +let URL_MATCHE = "https://na1.api.riotgames.com/lol/match/v3/timelines/by-match/"
why is match spelled weird...

2018-10-28 19:01 UTC, RichCherng commented on src/LoLAPI/api.js
> +export var calcCircumference = (radius) => {
I'm leaving it for now :D

2018-10-28 19:14 UTC, RichCherng commented
Closed, Changing branch name

2018-10-28 19:14 UTC, closed without merging